apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: application
  name: app-deploy
spec:
  replicas: 4
  selector:
    matchLabels:
      app: application
  template:
    metadata:
      labels:
        app: application
    spec:
      containers:
      - name: cont1
        image: deepagashe/application:latest
        ports:
          - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: abc
spec:
  type: LoadBalancer
  selector:
    app: application
  ports:
    - port: 80
      targetPort: 80
